### ISSUE TITLE
The isotope don't works well with my grid.

### ISSUE THREAD

**Issue by egermano** [mankindsoftware/angular-isotope#1]
I'm building a site with angular. In the main page and search results page has a recipes feed like a pinterest and I use the jQuery isotope plugin and angular-isotope, but I have 2 issues/problems.

In the main page a the grid cells do not have a fixed width, I use the min-width css property.

This is my CSS:

``` scss
    .recipe {
        width: $grid-width;
        min-height: 325px;
        height: auto;
        margin: $margin-top 0 $margin-bottom $ditter;
        float: left;
        position: relative;

        border: 1px solid #C3C3C3;
        @include border-radius(0 0 5px 5px);

        .avatar {
            position: absolute;
            top: -15px;
            width: $grid-width;
            margin: 0 auto;
            img {
                display: block;
                margin: 0 auto;
            }
        }

        .image {
            width: $grid-width - 2px;
            margin: 0 auto;
            overflow-x: hidden;
            img {
                width: $grid-width;
                margin: 0 auto;
            }
        }

        .name {
            font-family: Times;
            font-size: 20px;
            font-style: italic;
            font-weight: bold;
            text-align: center;
        }

        .recipe-controls {
            width: $grid-width;
            .star {
                font-size: 30px;
                margin: 15px;
            }
        }
    }
```

This is my angular template:

``` html
<div id="masonry" class="clearfix" isotope-container>
    <div isotope-item>
        ...
    </div>

    <div class="controls" isotope-item>
        ...
    </div>

    <div class="recipe" ng-repeat="recipe in recipes" isotope-item>
        <div class="avatar text-center">
            <a href="">
                <img class="img-circle" ng-src="http://graph.facebook.com/bruno.egermano/picture?type=normal" alt="">
            </a>
        </div>
        <div class="image">
            <a href="" ng-click="openRecipe(recipe.id)">
                <img ng-src="{{recipe.image}}" alt="{{recipe.name}}">
            </a>
        </div>
        <div class="name">
            <a href="" ng-click="openRecipe(recipe.id)">{{recipe.name}}</a>
        </div>
        <div class="recipe-controls">
            <i class="glyphicon  pull-right star" ng-class="{'glyphicon-star-empty': !recipe.star.stared, 'glyphicon-star': recipe.star.stared}">
                {{recipe.star.count}}
            </i>
        </div>
    </div>
</div>
```

And that is my screenshoot, the circles is the problems I got.
![isotope-issue1](https://f.cloud.github.com/assets/478100/1132799/62975a02-1bd1-11e3-8ca9-b4410a0ec602.jpg)

In this first problem. What am I doing wrong? 

The second problem, in the search result page, I have a filters, when the users change one of theirs, I call a ajax request and reload the collection.

When its occurs the isotope put all the items on one another, like that:
![screen shot 2013-09-12 at 14 38 55](https://f.cloud.github.com/assets/478100/1132845/44dbc498-1bd2-11e3-98b7-f785f5fc19e4.png)

The SCSS is the same and the HTML is much similar like the other problem.

Someone can help me?

**Comment by egermano** [comment]
Also in Stack Overflow 

http://stackoverflow.com/questions/18771038/the-angular-isotope-isotope-dont-works-well-with-my-grid

**Comment by egermano** [comment]
I found my mistake in the first problem.

I forgot to set the height of my image and the container. 

Now, my SCSS looks like that:

``` scss
    .recipe {
        width: $grid-width;
        height: auto;
        margin: $margin-top 0 $margin-bottom $ditter;
        float: left;
        position: relative;

        border: 1px solid #C3C3C3;
        @include border-radius(0 0 5px 5px);

        .avatar {
            position: absolute;
            top: -15px;
            width: $grid-width;
            margin: 0 auto;
            img {
                display: block;
                margin: 0 auto;
            }
        }

        .image {
            width: $grid-width - 2px;
            height: 235px;
            margin: 0 auto;
            overflow-x: hidden;
            img {
                width: $grid-width;
                margin: 0 auto;
            }
        }

        .name {
            font-family: Times;
            font-size: 20px;
            font-style: italic;
            font-weight: bold;
            text-align: center;
        }

        .recipe-controls {
            width: $grid-width;
            .star {
                font-size: 30px;
                margin: 15px;
            }
        }
    }
```

But the second problem is still happening.
